### ISSUE TITLE
Waiting for 6 bytes are Wire.requestFrom() is not correct.

### ISSUE THREAD

**Issue by Koepel** [adafruit/Adafruit_LSM303#3]
This line "while (Wire.available() < 6);" is twice in the code and it not correct.
After Wire.requestFrom() the I2C has completely finished and Wire.available() only returns the number of bytes in the buffer.
The return value of Wire.requestFrom() could be checked if 6 bytes are received. But waiting in a while loop to wait for 6 bytes is not correct.

Another Wire.requestFrom() is followed by Wire.endTransmission(). The Wire.endTransmission could (should) be removed.

**Comment by ladyada** [comment]
archiving this repo!
