### ISSUE TITLE
Wrong bit shift

### ISSUE THREAD

**Issue by NICOLASGON** [adafruit/Adafruit_LSM303#7]
Hello,

There is a problem whith these lines : 

  accelData.x = (xlo | (xhi << 8)) >> 4;
  accelData.y = (ylo | (yhi << 8)) >> 4;
  accelData.z = (zlo | (zhi << 8)) >> 4;

The bit shift of 4 isn't correct.
It's a 12 bits ADC you don't have to do a bit shift on the right ...
If the sensor is at the horizontal you have 0,61 kg/m² instead of 9,80 kg/m² ...
There is a coefficient 16 between the both wich correspond to the bit shift.

Tell me if i'am wrong,
Sincerely yours,
Nicolas Gonzalez

**Comment by guerby** [comment]
Hi, Nicolas patch seems correct to me, any way to get it committed?

Thanks for providing us with this great library :)

**Comment by microbuilder** [comment]
Values are left-aligned and indeed the shift can be removed, updated in https://github.com/adafruit/Adafruit_LSM303/commit/55c0e4b54614a5e5634c1674f26f8ff2522858f1
