### ISSUE TITLE
Is this library deprecated in favour of https://github.com/adafruit/Adafruit_LSM303DLHC or will be still maitained?

### ISSUE THREAD

**Issue by q2dg** [adafruit/Adafruit_LSM303#8]
I don't understand this duplicity (beyond one is based in Adafruit Sensors and the other isn't). I would like to know the future roadmap of both libraries.
Thanks.

**Comment by microbuilder** [comment]
You've pretty much summarised it ... one is based on the Adafruit_Sensor unified sensor system and returns values in standarized SI units and has a common data typedef, this is a bare bones library that returns raw values and doesn't have any external dependencies.  They are both useful in different situations, but we are planning on merging drivers that exist in both 'modes' into a single repo that exposes both unified and raw values.
